name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: "${{ steps.abc-number-generator.outputs.random-id}}"
    
runs:
  using: "composite"
  steps:
     - run: echo Hello ${{ inputs.who-to-greet }}.
       shell: bash
     - id: abc-number-generator
       run: echo "::set-output name=random-id::$(echo $RANDOM)"
       shell: bash
     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
       shell: bash 
     - run: echo "Completed Hello World Composite!"
       shell: bash
